name: SonarCloud Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'  # match your Go version

      - name: Install dependencies
        run: go mod tidy

      # Optional: If you add tests later
      # - name: Run tests and generate coverage
      #   run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=srz-vishnu_e-cart
            -Dsonar.organization=srz-innovations
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
